language: node_js
node_js:
- '8'
sudo: false
branches:
  only:
  - master
os:
- linux
cache:
  directories:
  - node_modules
install:
- yarn install
- yarn run build
script:
- yarn test --silent
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
